ccp-svc:
  runAsUid: "1000"
  namespace: health-check-app
  microservice:
    replicaCount: 3
    image:
      tag: 2.0
      repository: health-check-app
      pullPolicy: Always
      containerPort: 8080
      livenessProbe:
        path: "/"
        initialDelaySeconds: 1
        periodSeconds: 10
        port: 8080
      readinessProbe:
        path: "/"
        initialDelaySeconds: 1
        periodSeconds: 10
        port: 8080
    resources:
      limits:
        cpu: 128m
        memory: 128Mi
      requests:
        cpu: 32m
        memory: 32Mi
  service:
    type: NodePort
    port: 8080
  proxy:
    enabled: "false"
  ingress:
    enabled: "true"
